firewall:
   status: on
   user:
      binder: "@SessionUserBinder"
   routes:
      home:
         path: /
         methods: ["GET"]
         permitAll: true
      secured:
         path: /secured/**
         authenticated: true
      default:
         default: true
         permitAll: true